name: Test OIDC Authentication

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  descobrir-meu-id:
    runs-on: ubuntu-latest
    steps:
      - name: Extrair e Decodificar o Token OIDC real
        run: |
          # Captura o token oficial com a audiência da AWS
          JWT=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          
          # Desmembra e decodifica o cabeçalho do token (JWT) sem expor chaves sensíveis
          echo "=== CONTEÚDO REAL QUE O GITHUB ENVIA ==="
          echo $JWT | cut -d'.' -f2 | base64 --decode | jq .
